// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
)

const sessionUser = `-- name: SessionUser :one
SELECT u.id,u.email,u.locale,u.theme,s.csrf_token,u.locale_explicit
FROM sessions s JOIN users u ON u.id=s.user_id
WHERE s.token_hash=$1 AND s.expires_at>now()
`

type SessionUserRow struct {
	ID             string `json:"id"`
	Email          string `json:"email"`
	Locale         string `json:"locale"`
	Theme          string `json:"theme"`
	CsrfToken      string `json:"csrf_token"`
	LocaleExplicit bool   `json:"locale_explicit"`
}

func (q *Queries) SessionUser(ctx context.Context, tokenHash string) (SessionUserRow, error) {
	row := q.db.QueryRow(ctx, sessionUser, tokenHash)
	var i SessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Locale,
		&i.Theme,
		&i.CsrfToken,
		&i.LocaleExplicit,
	)
	return i, err
}

const tenantMembership = `-- name: TenantMembership :one
SELECT m.role, w.billing_account_id
FROM workspace_members m JOIN workspaces w ON w.id=m.workspace_id
WHERE m.workspace_id=$1 AND m.user_id=$2
AND w.deletion_requested_at IS NULL
FOR SHARE OF w,m
`

type TenantMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

type TenantMembershipRow struct {
	Role             string `json:"role"`
	BillingAccountID string `json:"billing_account_id"`
}

func (q *Queries) TenantMembership(ctx context.Context, arg TenantMembershipParams) (TenantMembershipRow, error) {
	row := q.db.QueryRow(ctx, tenantMembership, arg.WorkspaceID, arg.UserID)
	var i TenantMembershipRow
	err := row.Scan(&i.Role, &i.BillingAccountID)
	return i, err
}
